kind: pipeline
name: default

steps:
## Lint Helm Charts
- name: helm-chart-tests
  image: quay.io/helmpack/chart-testing:v2.1.0
  commands:
    - cp -R . /tmp/spring
    - ct lint --charts=/tmp/spring
    - helm template . > /tmp/template.yaml
    - helm package -d /tmp/packages .
